namespace FSTService.Persistence;

public static class PublicationGenerationStatus
{
    public const string Building = "building";
    public const string Ready = "ready";
    public const string Current = "current";
    public const string Retained = "retained";
    public const string Failed = "failed";
    public const string Retired = "retired";
}

public sealed record PublicationGenerationInfo(
    long PublicationId,
    long? ScrapeId,
    string Status,
    long? PreviousPublicationId,
    DateTime CreatedAtUtc,
    DateTime? SourceCutAtUtc,
    DateTime? ReadyAtUtc,
    DateTime? PublishedAtUtc,
    DateTime? FailedAtUtc,
    string? FailurePhase,
    string? FailureMessage);

public sealed record PublicationPointerState(
    long? CurrentPublicationId,
    long? PreviousPublicationId,
    long? WorkingPublicationId,
    long? PublishedScrapeId,
    DateTime? PublishedAtUtc);

public sealed record PublicationSurfaceBinding(
    long PublicationId,
    string SurfaceName,
    string BindingKind,
    string BindingJson,
    long? RowCount,
    string? ContentHash,
    string Status,
    DateTime BuiltAtUtc);

public static class PublicationGenerationSchema
{
    public const long AdvisoryLockKey = 5067481511116519500L;

    public const string Sql = """
        CREATE TABLE IF NOT EXISTS publication_generations (
            publication_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scrape_id              BIGINT UNIQUE REFERENCES scrape_log(id) ON DELETE CASCADE,
            status                 TEXT NOT NULL,
            previous_publication_id BIGINT
                REFERENCES publication_generations(publication_id) ON DELETE SET NULL,
            created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
            source_cut_at          TIMESTAMPTZ,
            ready_at               TIMESTAMPTZ,
            published_at           TIMESTAMPTZ,
            failed_at              TIMESTAMPTZ,
            failure_phase          TEXT,
            failure_message        TEXT,
            metadata               JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT ck_publication_generations_status
                CHECK (status IN ('building', 'ready', 'current', 'retained', 'failed', 'retired'))
        );

        CREATE INDEX IF NOT EXISTS ix_publication_generations_status
            ON publication_generations (status, publication_id DESC);

        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'publication_generations'::regclass
                  AND conname = 'publication_generations_scrape_id_fkey'
                  AND confdeltype <> 'c'
            ) THEN
                ALTER TABLE publication_generations
                    DROP CONSTRAINT publication_generations_scrape_id_fkey;
                ALTER TABLE publication_generations
                    ADD CONSTRAINT publication_generations_scrape_id_fkey
                    FOREIGN KEY (scrape_id)
                    REFERENCES scrape_log(id)
                    ON DELETE CASCADE;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'publication_generations'::regclass
                  AND conname = 'publication_generations_previous_publication_id_fkey'
                  AND confdeltype <> 'n'
            ) THEN
                ALTER TABLE publication_generations
                    DROP CONSTRAINT publication_generations_previous_publication_id_fkey;
                ALTER TABLE publication_generations
                    ADD CONSTRAINT publication_generations_previous_publication_id_fkey
                    FOREIGN KEY (previous_publication_id)
                    REFERENCES publication_generations(publication_id)
                    ON DELETE SET NULL;
            END IF;
        END $$;

        CREATE TABLE IF NOT EXISTS publication_surface_bindings (
            publication_id BIGINT NOT NULL
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            surface_name   TEXT NOT NULL,
            binding_kind   TEXT NOT NULL,
            binding_json   JSONB NOT NULL,
            row_count      BIGINT,
            content_hash   TEXT,
            status         TEXT NOT NULL DEFAULT 'ready',
            built_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (publication_id, surface_name),
            CONSTRAINT ck_publication_surface_binding_status
                CHECK (status IN ('building', 'ready', 'failed', 'retired'))
        );

        CREATE INDEX IF NOT EXISTS ix_publication_surface_bindings_surface
            ON publication_surface_bindings (surface_name, publication_id DESC);

        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS current_publication_id BIGINT
                REFERENCES publication_generations(publication_id);
        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS previous_publication_id BIGINT
                REFERENCES publication_generations(publication_id) ON DELETE SET NULL;
        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS working_publication_id BIGINT
                REFERENCES publication_generations(publication_id);

        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'scrape_publication_state'::regclass
                  AND conname = 'scrape_publication_state_previous_publication_id_fkey'
                  AND confdeltype <> 'n'
            ) THEN
                ALTER TABLE scrape_publication_state
                    DROP CONSTRAINT scrape_publication_state_previous_publication_id_fkey;
                ALTER TABLE scrape_publication_state
                    ADD CONSTRAINT scrape_publication_state_previous_publication_id_fkey
                    FOREIGN KEY (previous_publication_id)
                    REFERENCES publication_generations(publication_id)
                    ON DELETE SET NULL;
            END IF;
        END $$;

        INSERT INTO publication_generations (
            scrape_id,
            status,
            created_at,
            source_cut_at,
            ready_at,
            published_at)
        SELECT
            publication.published_scrape_id,
            'current',
            COALESCE(scrape.started_at, publication.published_at, now()),
            scrape.completed_at,
            scrape.completed_at,
            publication.published_at
        FROM scrape_publication_state publication
        LEFT JOIN scrape_log scrape
          ON scrape.id = publication.published_scrape_id
        WHERE publication.id = TRUE
          AND publication.published_scrape_id IS NOT NULL
        ON CONFLICT (scrape_id) DO UPDATE SET
            status = CASE
                WHEN publication_generations.status = 'retired'
                    THEN publication_generations.status
                ELSE 'current'
            END,
            published_at = COALESCE(
                publication_generations.published_at,
                EXCLUDED.published_at),
            ready_at = COALESCE(
                publication_generations.ready_at,
                EXCLUDED.ready_at);

        UPDATE scrape_publication_state publication
        SET current_publication_id = generation.publication_id,
            updated_at = now()
        FROM publication_generations generation
        WHERE publication.id = TRUE
          AND publication.published_scrape_id = generation.scrape_id
          AND publication.current_publication_id IS NULL;
        """;
}
