namespace FSTService.Persistence;

public static class PublicationGenerationStatus
{
    public const string Building = "building";
    public const string Ready = "ready";
    public const string Current = "current";
    public const string Retained = "retained";
    public const string Failed = "failed";
    public const string Retired = "retired";
}

public sealed record PublicationGenerationInfo(
    long PublicationId,
    long? ScrapeId,
    string Status,
    long? PreviousPublicationId,
    DateTime CreatedAtUtc,
    DateTime? SourceCutAtUtc,
    DateTime? ReadyAtUtc,
    DateTime? PublishedAtUtc,
    DateTime? FailedAtUtc,
    string? FailurePhase,
    string? FailureMessage);

public sealed record PublicationPointerState(
    long? CurrentPublicationId,
    long? PreviousPublicationId,
    long? WorkingPublicationId,
    long? PublishedScrapeId,
    DateTime? PublishedAtUtc);

public sealed record PublicationSurfaceBinding(
    long PublicationId,
    string SurfaceName,
    string BindingKind,
    string BindingJson,
    long? RowCount,
    string? ContentHash,
    string Status,
    DateTime BuiltAtUtc);

public sealed record PublicationSongCatalogInfo(
    long PublicationId,
    long ScrapeId,
    long CatalogVersion,
    int SchemaVersion,
    string CatalogJson,
    string ContentHash,
    int SongCount,
    DateTime SourceCapturedAtUtc);

public static class PublicationGenerationSchema
{
    public const long AdvisoryLockKey = 5067481511116519500L;
    public const long CacheBuildAdvisoryLockBase = 5067481511116520000L;

    public const string Sql = """
        CREATE TABLE IF NOT EXISTS publication_generations (
            publication_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scrape_id              BIGINT UNIQUE REFERENCES scrape_log(id) ON DELETE CASCADE,
            status                 TEXT NOT NULL,
            previous_publication_id BIGINT
                REFERENCES publication_generations(publication_id) ON DELETE SET NULL,
            created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
            source_cut_at          TIMESTAMPTZ,
            ready_at               TIMESTAMPTZ,
            published_at           TIMESTAMPTZ,
            failed_at              TIMESTAMPTZ,
            failure_phase          TEXT,
            failure_message        TEXT,
            metadata               JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT ck_publication_generations_status
                CHECK (status IN ('building', 'ready', 'current', 'retained', 'failed', 'retired'))
        );

        CREATE INDEX IF NOT EXISTS ix_publication_generations_status
            ON publication_generations (status, publication_id DESC);

        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'publication_generations'::regclass
                  AND conname = 'publication_generations_scrape_id_fkey'
                  AND confdeltype <> 'c'
            ) THEN
                ALTER TABLE publication_generations
                    DROP CONSTRAINT publication_generations_scrape_id_fkey;
                ALTER TABLE publication_generations
                    ADD CONSTRAINT publication_generations_scrape_id_fkey
                    FOREIGN KEY (scrape_id)
                    REFERENCES scrape_log(id)
                    ON DELETE CASCADE;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'publication_generations'::regclass
                  AND conname = 'publication_generations_previous_publication_id_fkey'
                  AND confdeltype <> 'n'
            ) THEN
                ALTER TABLE publication_generations
                    DROP CONSTRAINT publication_generations_previous_publication_id_fkey;
                ALTER TABLE publication_generations
                    ADD CONSTRAINT publication_generations_previous_publication_id_fkey
                    FOREIGN KEY (previous_publication_id)
                    REFERENCES publication_generations(publication_id)
                    ON DELETE SET NULL;
            END IF;
        END $$;

        CREATE TABLE IF NOT EXISTS publication_surface_bindings (
            publication_id BIGINT NOT NULL
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            surface_name   TEXT NOT NULL,
            binding_kind   TEXT NOT NULL,
            binding_json   JSONB NOT NULL,
            row_count      BIGINT,
            content_hash   TEXT,
            status         TEXT NOT NULL DEFAULT 'ready',
            built_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (publication_id, surface_name),
            CONSTRAINT ck_publication_surface_binding_status
                CHECK (status IN ('building', 'ready', 'failed', 'retired'))
        );

        CREATE INDEX IF NOT EXISTS ix_publication_surface_bindings_surface
            ON publication_surface_bindings (surface_name, publication_id DESC);

        CREATE SEQUENCE IF NOT EXISTS song_catalog_version_seq;

        CREATE TABLE IF NOT EXISTS live_song_catalog (
            id              BOOLEAN     PRIMARY KEY DEFAULT TRUE CHECK (id),
            catalog_version BIGINT      NOT NULL
                DEFAULT nextval('song_catalog_version_seq'),
            schema_version  INTEGER     NOT NULL DEFAULT 1,
            catalog_json    JSONB       NOT NULL,
            content_hash    TEXT        NOT NULL,
            song_count      INTEGER     NOT NULL,
            source_kind     TEXT        NOT NULL
                DEFAULT 'legacy_columns_reconstructed',
            is_exact        BOOLEAN     NOT NULL DEFAULT FALSE,
            captured_at     TIMESTAMPTZ NOT NULL,
            CONSTRAINT ck_live_song_catalog_count
                CHECK (song_count >= 0),
            CONSTRAINT ck_live_song_catalog_hash
                CHECK (content_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT ck_live_song_catalog_source_kind
                CHECK (source_kind IN (
                    'provider_exact',
                    'legacy_columns_reconstructed'))
        );

        CREATE TABLE IF NOT EXISTS publication_song_catalog (
            publication_id    BIGINT      PRIMARY KEY
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            catalog_version   BIGINT      NOT NULL
                DEFAULT nextval('song_catalog_version_seq'),
            schema_version    INTEGER     NOT NULL DEFAULT 1,
            catalog_json      JSONB       NOT NULL,
            content_hash      TEXT        NOT NULL,
            song_count        INTEGER     NOT NULL,
            source_kind       TEXT        NOT NULL
                DEFAULT 'legacy_publication_reconstructed',
            is_exact          BOOLEAN     NOT NULL DEFAULT FALSE,
            source_captured_at TIMESTAMPTZ NOT NULL,
            captured_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_publication_song_catalog_count
                CHECK (song_count >= 0),
            CONSTRAINT ck_publication_song_catalog_hash
                CHECK (content_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT ck_publication_song_catalog_source_kind
                CHECK (source_kind IN (
                    'provider_exact',
                    'legacy_publication_reconstructed'))
        );

        ALTER TABLE live_song_catalog
            ADD COLUMN IF NOT EXISTS catalog_version BIGINT;
        ALTER TABLE live_song_catalog
            ADD COLUMN IF NOT EXISTS schema_version INTEGER;
        ALTER TABLE live_song_catalog
            ADD COLUMN IF NOT EXISTS source_kind TEXT;
        ALTER TABLE live_song_catalog
            ADD COLUMN IF NOT EXISTS is_exact BOOLEAN;

        UPDATE live_song_catalog
        SET catalog_version = COALESCE(
                catalog_version,
                nextval('song_catalog_version_seq')),
            schema_version = COALESCE(schema_version, 1),
            source_kind = COALESCE(
                source_kind,
                'legacy_columns_reconstructed'),
            is_exact = COALESCE(is_exact, FALSE);

        ALTER TABLE live_song_catalog
            ALTER COLUMN catalog_version SET NOT NULL;
        ALTER TABLE live_song_catalog
            ALTER COLUMN catalog_version
            SET DEFAULT nextval('song_catalog_version_seq');
        ALTER TABLE live_song_catalog
            ALTER COLUMN schema_version SET NOT NULL;
        ALTER TABLE live_song_catalog
            ALTER COLUMN schema_version SET DEFAULT 1;
        ALTER TABLE live_song_catalog
            ALTER COLUMN source_kind SET NOT NULL;
        ALTER TABLE live_song_catalog
            ALTER COLUMN source_kind
            SET DEFAULT 'legacy_columns_reconstructed';
        ALTER TABLE live_song_catalog
            ALTER COLUMN is_exact SET NOT NULL;
        ALTER TABLE live_song_catalog
            ALTER COLUMN is_exact SET DEFAULT FALSE;

        ALTER TABLE publication_song_catalog
            ADD COLUMN IF NOT EXISTS catalog_version BIGINT;
        ALTER TABLE publication_song_catalog
            ADD COLUMN IF NOT EXISTS schema_version INTEGER;
        ALTER TABLE publication_song_catalog
            ADD COLUMN IF NOT EXISTS source_kind TEXT;
        ALTER TABLE publication_song_catalog
            ADD COLUMN IF NOT EXISTS is_exact BOOLEAN;

        UPDATE publication_song_catalog
        SET catalog_version = COALESCE(
                catalog_version,
                nextval('song_catalog_version_seq')),
            schema_version = COALESCE(schema_version, 1),
            source_kind = COALESCE(
                source_kind,
                'legacy_publication_reconstructed'),
            is_exact = COALESCE(is_exact, FALSE);

        ALTER TABLE publication_song_catalog
            ALTER COLUMN catalog_version SET NOT NULL;
        ALTER TABLE publication_song_catalog
            ALTER COLUMN catalog_version
            SET DEFAULT nextval('song_catalog_version_seq');
        ALTER TABLE publication_song_catalog
            ALTER COLUMN schema_version SET NOT NULL;
        ALTER TABLE publication_song_catalog
            ALTER COLUMN schema_version SET DEFAULT 1;
        ALTER TABLE publication_song_catalog
            ALTER COLUMN source_kind SET NOT NULL;
        ALTER TABLE publication_song_catalog
            ALTER COLUMN source_kind
            SET DEFAULT 'legacy_publication_reconstructed';
        ALTER TABLE publication_song_catalog
            ALTER COLUMN is_exact SET NOT NULL;
        ALTER TABLE publication_song_catalog
            ALTER COLUMN is_exact SET DEFAULT FALSE;

        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'live_song_catalog'::regclass
                  AND conname = 'ck_live_song_catalog_source_kind'
            ) THEN
                ALTER TABLE live_song_catalog
                    ADD CONSTRAINT ck_live_song_catalog_source_kind
                    CHECK (source_kind IN (
                        'provider_exact',
                        'legacy_columns_reconstructed'));
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'publication_song_catalog'::regclass
                  AND conname = 'ck_publication_song_catalog_source_kind'
            ) THEN
                ALTER TABLE publication_song_catalog
                    ADD CONSTRAINT ck_publication_song_catalog_source_kind
                    CHECK (source_kind IN (
                        'provider_exact',
                        'legacy_publication_reconstructed'));
            END IF;
        END $$;

        CREATE OR REPLACE FUNCTION normalize_legacy_live_song_catalog_write()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF (
                NEW.catalog_json IS DISTINCT FROM OLD.catalog_json
                OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
                OR NEW.song_count IS DISTINCT FROM OLD.song_count
            )
            AND NEW.catalog_version = OLD.catalog_version
            THEN
                NEW.catalog_version :=
                    nextval('song_catalog_version_seq');
                NEW.schema_version := 1;
                NEW.source_kind := 'legacy_columns_reconstructed';
                NEW.is_exact := FALSE;
            END IF;
            RETURN NEW;
        END $$;

        DROP TRIGGER IF EXISTS trg_normalize_legacy_live_song_catalog_write
            ON live_song_catalog;
        CREATE TRIGGER trg_normalize_legacy_live_song_catalog_write
        BEFORE UPDATE ON live_song_catalog
        FOR EACH ROW
        EXECUTE FUNCTION normalize_legacy_live_song_catalog_write();

        CREATE TABLE IF NOT EXISTS publication_api_response_cache (
            publication_id BIGINT NOT NULL
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            cache_key   TEXT        NOT NULL,
            json_data   BYTEA       NOT NULL,
            etag        TEXT        NOT NULL,
            cached_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (publication_id, cache_key)
        );

        CREATE TABLE IF NOT EXISTS publication_api_response_cache_staging (
            publication_id BIGINT NOT NULL
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            cache_key   TEXT        NOT NULL,
            json_data   BYTEA       NOT NULL,
            etag        TEXT        NOT NULL,
            cached_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (publication_id, cache_key)
        );

        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS current_publication_id BIGINT
                REFERENCES publication_generations(publication_id);
        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS previous_publication_id BIGINT
                REFERENCES publication_generations(publication_id) ON DELETE SET NULL;
        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS working_publication_id BIGINT
                REFERENCES publication_generations(publication_id);

        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'scrape_publication_state'::regclass
                  AND conname = 'scrape_publication_state_previous_publication_id_fkey'
                  AND confdeltype <> 'n'
            ) THEN
                ALTER TABLE scrape_publication_state
                    DROP CONSTRAINT scrape_publication_state_previous_publication_id_fkey;
                ALTER TABLE scrape_publication_state
                    ADD CONSTRAINT scrape_publication_state_previous_publication_id_fkey
                    FOREIGN KEY (previous_publication_id)
                    REFERENCES publication_generations(publication_id)
                    ON DELETE SET NULL;
            END IF;
        END $$;

        INSERT INTO publication_generations (
            scrape_id,
            status,
            created_at,
            source_cut_at,
            ready_at,
            published_at)
        SELECT
            publication.published_scrape_id,
            'current',
            COALESCE(scrape.started_at, publication.published_at, now()),
            scrape.completed_at,
            scrape.completed_at,
            publication.published_at
        FROM scrape_publication_state publication
        LEFT JOIN scrape_log scrape
          ON scrape.id = publication.published_scrape_id
        WHERE publication.id = TRUE
          AND publication.published_scrape_id IS NOT NULL
        ON CONFLICT (scrape_id) DO UPDATE SET
            status = CASE
                WHEN publication_generations.status = 'retired'
                    THEN publication_generations.status
                ELSE 'current'
            END,
            published_at = COALESCE(
                publication_generations.published_at,
                EXCLUDED.published_at),
            ready_at = COALESCE(
                publication_generations.ready_at,
                EXCLUDED.ready_at);

        UPDATE scrape_publication_state publication
        SET current_publication_id = generation.publication_id,
            updated_at = now()
        FROM publication_generations generation
        WHERE publication.id = TRUE
          AND publication.published_scrape_id = generation.scrape_id
          AND publication.current_publication_id IS NULL;

        WITH canonical_songs AS (
            SELECT
                song.song_id,
                jsonb_strip_nulls(jsonb_build_object(
                    '_title', song.title,
                    'track', jsonb_strip_nulls(jsonb_build_object(
                        'tt', song.title,
                        'ry', song.release_year,
                        'su', song.song_id,
                        'in', CASE
                            WHEN song.lead_diff IS NOT NULL
                              OR song.bass_diff IS NOT NULL
                              OR song.vocals_diff IS NOT NULL
                              OR song.drums_diff IS NOT NULL
                              OR song.pro_lead_diff IS NOT NULL
                              OR song.pro_bass_diff IS NOT NULL
                              OR song.plastic_guitar_diff IS NOT NULL
                              OR song.plastic_bass_diff IS NOT NULL
                              OR song.plastic_drums_diff IS NOT NULL
                              OR song.pro_vocals_diff IS NOT NULL
                            THEN jsonb_strip_nulls(jsonb_build_object(
                                'pb', COALESCE(
                                    song.plastic_bass_diff,
                                    song.pro_bass_diff),
                                'pd', song.plastic_drums_diff,
                                'vl', song.vocals_diff,
                                'pg', COALESCE(
                                    song.plastic_guitar_diff,
                                    song.pro_lead_diff),
                                'gr', song.lead_diff,
                                'ds', song.drums_diff,
                                'ba', song.bass_diff,
                                'bd', song.pro_vocals_diff))
                            ELSE NULL
                        END,
                        'mt', song.tempo,
                        'an', song.artist)),
                    '_activeDate', NULLIF(song.active_date, ''),
                    'lastModified', NULLIF(song.last_modified, '')))
                    AS song_json
            FROM songs song
            WHERE NULLIF(song.song_id, '') IS NOT NULL
        ),
        legacy_payload AS (
            SELECT
                jsonb_build_object(
                    'schemaVersion', 1,
                    'songs', COALESCE(
                        jsonb_agg(song_json ORDER BY song_id),
                        '[]'::jsonb)) AS catalog_json,
                COUNT(*)::integer AS song_count
            FROM canonical_songs
        )
        INSERT INTO live_song_catalog (
            id, catalog_version, schema_version, catalog_json,
            content_hash, song_count, source_kind, is_exact, captured_at)
        SELECT
            TRUE,
            nextval('song_catalog_version_seq'),
            1,
            catalog_json,
            encode(
                digest(convert_to(catalog_json::text, 'UTF8'), 'sha256'),
                'hex'),
            song_count,
            'legacy_columns_reconstructed',
            FALSE,
            now()
        FROM legacy_payload
        ON CONFLICT (id) DO NOTHING;

        WITH bootstrap_publications AS (
            SELECT current_publication_id AS publication_id
            FROM scrape_publication_state
            WHERE id = TRUE
              AND current_publication_id IS NOT NULL
            UNION
            SELECT working_publication_id
            FROM scrape_publication_state
            WHERE id = TRUE
              AND working_publication_id IS NOT NULL
        )
        INSERT INTO publication_song_catalog (
            publication_id, catalog_version, schema_version, catalog_json,
            content_hash, song_count, source_kind, is_exact,
            source_captured_at, captured_at)
        SELECT
            publication.publication_id,
            catalog.catalog_version,
            catalog.schema_version,
            catalog.catalog_json,
            catalog.content_hash,
            catalog.song_count,
            'legacy_publication_reconstructed',
            FALSE,
            catalog.captured_at,
            now()
        FROM bootstrap_publications publication
        CROSS JOIN live_song_catalog catalog
        WHERE catalog.id = TRUE
        ON CONFLICT (publication_id) DO NOTHING;

        INSERT INTO publication_surface_bindings (
            publication_id, surface_name, binding_kind, binding_json,
            row_count, content_hash, status, built_at)
        SELECT
            snapshot.publication_id,
            'song_catalog',
            'legacy_reconstructed_catalog',
            jsonb_build_object(
                'table', 'publication_song_catalog',
                'publicationId', snapshot.publication_id,
                'catalogVersion', snapshot.catalog_version,
                'schemaVersion', snapshot.schema_version,
                'sourceKind', snapshot.source_kind,
                'isExact', false,
                'sourceCapturedAt', snapshot.source_captured_at),
            snapshot.song_count,
            snapshot.content_hash,
            'building',
            snapshot.captured_at
        FROM publication_song_catalog snapshot
        JOIN scrape_publication_state publication
          ON publication.id = TRUE
         AND snapshot.publication_id IN (
             publication.current_publication_id,
             publication.working_publication_id)
        WHERE NOT snapshot.is_exact
        ON CONFLICT (publication_id, surface_name) DO UPDATE SET
            binding_kind = EXCLUDED.binding_kind,
            binding_json = EXCLUDED.binding_json,
            row_count = EXCLUDED.row_count,
            content_hash = EXCLUDED.content_hash,
            status = EXCLUDED.status,
            built_at = EXCLUDED.built_at
        WHERE publication_surface_bindings.status <> 'retired'
          AND (
              publication_surface_bindings.binding_kind IN (
                  'legacy_live_unversioned',
                  'generation_catalog_snapshot',
                  'legacy_reconstructed_catalog')
              OR publication_surface_bindings.status IN (
                  'building',
                  'failed'));

        UPDATE publication_surface_bindings binding
        SET binding_kind = 'legacy_reconstructed_catalog',
            binding_json = jsonb_build_object(
                'table', 'publication_song_catalog',
                'publicationId', snapshot.publication_id,
                'catalogVersion', snapshot.catalog_version,
                'schemaVersion', snapshot.schema_version,
                'sourceKind', snapshot.source_kind,
                'isExact', false,
                'sourceCapturedAt', snapshot.source_captured_at),
            row_count = snapshot.song_count,
            content_hash = snapshot.content_hash,
            status = 'building',
            built_at = snapshot.captured_at
        FROM publication_song_catalog snapshot
        WHERE binding.publication_id = snapshot.publication_id
          AND binding.surface_name = 'song_catalog'
          AND NOT snapshot.is_exact
          AND binding.status NOT IN ('failed', 'retired');

        DO $$
        DECLARE
            current_id BIGINT;
            binding_built_at TIMESTAMPTZ;
            existing_binding_kind TEXT;
            legacy_cached_at TIMESTAMPTZ;
            legacy_row_count BIGINT;
            legacy_content_hash TEXT;
            generation_row_count BIGINT;
            generation_content_hash TEXT;
        BEGIN
            SELECT current_publication_id
            INTO current_id
            FROM scrape_publication_state
            WHERE id = TRUE;

            IF current_id IS NULL THEN
                RETURN;
            END IF;

            SELECT binding.built_at, binding.binding_kind
            INTO binding_built_at, existing_binding_kind
            FROM publication_surface_bindings binding
            WHERE binding.publication_id = current_id
              AND binding.surface_name = 'api_response_cache';

            SELECT
                MAX(cached_at),
                COUNT(*),
                md5(COALESCE(
                    string_agg(
                        cache_key || ':' || etag,
                        '|' ORDER BY cache_key),
                    ''))
            INTO legacy_cached_at, legacy_row_count, legacy_content_hash
            FROM api_response_cache;

            SELECT
                COUNT(*),
                md5(COALESCE(
                    string_agg(
                        cache_key || ':' || etag,
                        '|' ORDER BY cache_key),
                    ''))
            INTO generation_row_count, generation_content_hash
            FROM publication_api_response_cache
            WHERE publication_id = current_id;

            IF binding_built_at IS NULL
               OR existing_binding_kind IN (
                    'inherited_previous_publication',
                    'inherited_generation_cache')
               OR generation_row_count IS DISTINCT FROM legacy_row_count
               OR generation_content_hash IS DISTINCT FROM legacy_content_hash
               OR legacy_cached_at IS NOT NULL
                  AND legacy_cached_at > binding_built_at
            THEN
                DELETE FROM publication_api_response_cache
                WHERE publication_id = current_id;

                INSERT INTO publication_api_response_cache (
                    publication_id, cache_key, json_data, etag, cached_at)
                SELECT
                    current_id,
                    cache_key,
                    json_data,
                    etag,
                    cached_at
                FROM api_response_cache;

                INSERT INTO publication_surface_bindings (
                    publication_id, surface_name, binding_kind, binding_json,
                    row_count, content_hash, status, built_at)
                VALUES (
                    current_id,
                    'api_response_cache',
                    'legacy_current_table_reconciled',
                    jsonb_build_object(
                        'table', 'publication_api_response_cache',
                        'sourceTable', 'api_response_cache',
                        'publicationId', current_id),
                    legacy_row_count,
                    legacy_content_hash,
                    'ready',
                    now())
                ON CONFLICT (publication_id, surface_name) DO UPDATE SET
                    binding_kind = EXCLUDED.binding_kind,
                    binding_json = EXCLUDED.binding_json,
                    row_count = EXCLUDED.row_count,
                    content_hash = EXCLUDED.content_hash,
                    status = EXCLUDED.status,
                    built_at = EXCLUDED.built_at;
            END IF;
        END $$;

        DELETE FROM publication_api_response_cache cache
        USING scrape_publication_state publication
        WHERE publication.id = TRUE
          AND cache.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.working_publication_id;

        DELETE FROM publication_api_response_cache_staging cache
        USING scrape_publication_state publication
        WHERE publication.id = TRUE
          AND cache.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.working_publication_id;

        DELETE FROM publication_song_catalog catalog
        USING scrape_publication_state publication
        WHERE publication.id = TRUE
          AND catalog.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND catalog.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND catalog.publication_id IS DISTINCT FROM
              publication.working_publication_id;

        UPDATE publication_surface_bindings binding
        SET binding_kind = 'retired_generation_catalog',
            binding_json = jsonb_build_object(
                'table', 'publication_song_catalog',
                'retired', true),
            row_count = 0,
            content_hash = NULL,
            status = 'retired',
            built_at = now()
        FROM scrape_publication_state publication
        WHERE publication.id = TRUE
          AND binding.surface_name = 'song_catalog'
          AND binding.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND binding.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND binding.publication_id IS DISTINCT FROM
              publication.working_publication_id
          AND binding.status <> 'retired';

        UPDATE publication_surface_bindings binding
        SET binding_kind = 'retired_generation_cache',
            binding_json = jsonb_build_object(
                'table', 'publication_api_response_cache',
                'retired', true),
            row_count = 0,
            content_hash = NULL,
            status = 'retired',
            built_at = now()
        FROM scrape_publication_state publication
        WHERE publication.id = TRUE
          AND binding.surface_name = 'api_response_cache'
          AND binding.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND binding.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND binding.publication_id IS DISTINCT FROM
              publication.working_publication_id
          AND binding.status <> 'retired';
        """;
}
