namespace FSTService.Persistence;

public static class PublicationGenerationStatus
{
    public const string Building = "building";
    public const string Ready = "ready";
    public const string Current = "current";
    public const string Retained = "retained";
    public const string Failed = "failed";
    public const string Retired = "retired";
}

public sealed record PublicationGenerationInfo(
    long PublicationId,
    long? ScrapeId,
    string Status,
    long? PreviousPublicationId,
    DateTime CreatedAtUtc,
    DateTime? SourceCutAtUtc,
    DateTime? ReadyAtUtc,
    DateTime? PublishedAtUtc,
    DateTime? FailedAtUtc,
    string? FailurePhase,
    string? FailureMessage);

public sealed record PublicationPointerState(
    long? CurrentPublicationId,
    long? PreviousPublicationId,
    long? WorkingPublicationId,
    long? PublishedScrapeId,
    DateTime? PublishedAtUtc);

public sealed record PublicationSurfaceBinding(
    long PublicationId,
    string SurfaceName,
    string BindingKind,
    string BindingJson,
    long? RowCount,
    string? ContentHash,
    string Status,
    DateTime BuiltAtUtc);

public static class PublicationGenerationSchema
{
    public const long AdvisoryLockKey = 5067481511116519500L;
    public const long CacheBuildAdvisoryLockBase = 5067481511116520000L;

    public const string Sql = """
        CREATE TABLE IF NOT EXISTS publication_generations (
            publication_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scrape_id              BIGINT UNIQUE REFERENCES scrape_log(id) ON DELETE CASCADE,
            status                 TEXT NOT NULL,
            previous_publication_id BIGINT
                REFERENCES publication_generations(publication_id) ON DELETE SET NULL,
            created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
            source_cut_at          TIMESTAMPTZ,
            ready_at               TIMESTAMPTZ,
            published_at           TIMESTAMPTZ,
            failed_at              TIMESTAMPTZ,
            failure_phase          TEXT,
            failure_message        TEXT,
            metadata               JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT ck_publication_generations_status
                CHECK (status IN ('building', 'ready', 'current', 'retained', 'failed', 'retired'))
        );

        CREATE INDEX IF NOT EXISTS ix_publication_generations_status
            ON publication_generations (status, publication_id DESC);

        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'publication_generations'::regclass
                  AND conname = 'publication_generations_scrape_id_fkey'
                  AND confdeltype <> 'c'
            ) THEN
                ALTER TABLE publication_generations
                    DROP CONSTRAINT publication_generations_scrape_id_fkey;
                ALTER TABLE publication_generations
                    ADD CONSTRAINT publication_generations_scrape_id_fkey
                    FOREIGN KEY (scrape_id)
                    REFERENCES scrape_log(id)
                    ON DELETE CASCADE;
            END IF;

            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'publication_generations'::regclass
                  AND conname = 'publication_generations_previous_publication_id_fkey'
                  AND confdeltype <> 'n'
            ) THEN
                ALTER TABLE publication_generations
                    DROP CONSTRAINT publication_generations_previous_publication_id_fkey;
                ALTER TABLE publication_generations
                    ADD CONSTRAINT publication_generations_previous_publication_id_fkey
                    FOREIGN KEY (previous_publication_id)
                    REFERENCES publication_generations(publication_id)
                    ON DELETE SET NULL;
            END IF;
        END $$;

        CREATE TABLE IF NOT EXISTS publication_surface_bindings (
            publication_id BIGINT NOT NULL
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            surface_name   TEXT NOT NULL,
            binding_kind   TEXT NOT NULL,
            binding_json   JSONB NOT NULL,
            row_count      BIGINT,
            content_hash   TEXT,
            status         TEXT NOT NULL DEFAULT 'ready',
            built_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (publication_id, surface_name),
            CONSTRAINT ck_publication_surface_binding_status
                CHECK (status IN ('building', 'ready', 'failed', 'retired'))
        );

        CREATE INDEX IF NOT EXISTS ix_publication_surface_bindings_surface
            ON publication_surface_bindings (surface_name, publication_id DESC);

        CREATE TABLE IF NOT EXISTS publication_api_response_cache (
            publication_id BIGINT NOT NULL
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            cache_key   TEXT        NOT NULL,
            json_data   BYTEA       NOT NULL,
            etag        TEXT        NOT NULL,
            cached_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (publication_id, cache_key)
        );

        CREATE TABLE IF NOT EXISTS publication_api_response_cache_staging (
            publication_id BIGINT NOT NULL
                REFERENCES publication_generations(publication_id) ON DELETE CASCADE,
            cache_key   TEXT        NOT NULL,
            json_data   BYTEA       NOT NULL,
            etag        TEXT        NOT NULL,
            cached_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (publication_id, cache_key)
        );

        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS current_publication_id BIGINT
                REFERENCES publication_generations(publication_id);
        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS previous_publication_id BIGINT
                REFERENCES publication_generations(publication_id) ON DELETE SET NULL;
        ALTER TABLE scrape_publication_state
            ADD COLUMN IF NOT EXISTS working_publication_id BIGINT
                REFERENCES publication_generations(publication_id);

        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'scrape_publication_state'::regclass
                  AND conname = 'scrape_publication_state_previous_publication_id_fkey'
                  AND confdeltype <> 'n'
            ) THEN
                ALTER TABLE scrape_publication_state
                    DROP CONSTRAINT scrape_publication_state_previous_publication_id_fkey;
                ALTER TABLE scrape_publication_state
                    ADD CONSTRAINT scrape_publication_state_previous_publication_id_fkey
                    FOREIGN KEY (previous_publication_id)
                    REFERENCES publication_generations(publication_id)
                    ON DELETE SET NULL;
            END IF;
        END $$;

        INSERT INTO publication_generations (
            scrape_id,
            status,
            created_at,
            source_cut_at,
            ready_at,
            published_at)
        SELECT
            publication.published_scrape_id,
            'current',
            COALESCE(scrape.started_at, publication.published_at, now()),
            scrape.completed_at,
            scrape.completed_at,
            publication.published_at
        FROM scrape_publication_state publication
        LEFT JOIN scrape_log scrape
          ON scrape.id = publication.published_scrape_id
        WHERE publication.id = TRUE
          AND publication.published_scrape_id IS NOT NULL
        ON CONFLICT (scrape_id) DO UPDATE SET
            status = CASE
                WHEN publication_generations.status = 'retired'
                    THEN publication_generations.status
                ELSE 'current'
            END,
            published_at = COALESCE(
                publication_generations.published_at,
                EXCLUDED.published_at),
            ready_at = COALESCE(
                publication_generations.ready_at,
                EXCLUDED.ready_at);

        UPDATE scrape_publication_state publication
        SET current_publication_id = generation.publication_id,
            updated_at = now()
        FROM publication_generations generation
        WHERE publication.id = TRUE
          AND publication.published_scrape_id = generation.scrape_id
          AND publication.current_publication_id IS NULL;

        DO $$
        DECLARE
            current_id BIGINT;
            binding_built_at TIMESTAMPTZ;
            existing_binding_kind TEXT;
            legacy_cached_at TIMESTAMPTZ;
            legacy_row_count BIGINT;
            legacy_content_hash TEXT;
            generation_row_count BIGINT;
            generation_content_hash TEXT;
        BEGIN
            SELECT current_publication_id
            INTO current_id
            FROM scrape_publication_state
            WHERE id = TRUE;

            IF current_id IS NULL THEN
                RETURN;
            END IF;

            SELECT binding.built_at, binding.binding_kind
            INTO binding_built_at, existing_binding_kind
            FROM publication_surface_bindings binding
            WHERE binding.publication_id = current_id
              AND binding.surface_name = 'api_response_cache';

            SELECT
                MAX(cached_at),
                COUNT(*),
                md5(COALESCE(
                    string_agg(
                        cache_key || ':' || etag,
                        '|' ORDER BY cache_key),
                    ''))
            INTO legacy_cached_at, legacy_row_count, legacy_content_hash
            FROM api_response_cache;

            SELECT
                COUNT(*),
                md5(COALESCE(
                    string_agg(
                        cache_key || ':' || etag,
                        '|' ORDER BY cache_key),
                    ''))
            INTO generation_row_count, generation_content_hash
            FROM publication_api_response_cache
            WHERE publication_id = current_id;

            IF binding_built_at IS NULL
               OR existing_binding_kind IN (
                    'inherited_previous_publication',
                    'inherited_generation_cache')
               OR generation_row_count IS DISTINCT FROM legacy_row_count
               OR generation_content_hash IS DISTINCT FROM legacy_content_hash
               OR legacy_cached_at IS NOT NULL
                  AND legacy_cached_at > binding_built_at
            THEN
                DELETE FROM publication_api_response_cache
                WHERE publication_id = current_id;

                INSERT INTO publication_api_response_cache (
                    publication_id, cache_key, json_data, etag, cached_at)
                SELECT
                    current_id,
                    cache_key,
                    json_data,
                    etag,
                    cached_at
                FROM api_response_cache;

                INSERT INTO publication_surface_bindings (
                    publication_id, surface_name, binding_kind, binding_json,
                    row_count, content_hash, status, built_at)
                VALUES (
                    current_id,
                    'api_response_cache',
                    'legacy_current_table_reconciled',
                    jsonb_build_object(
                        'table', 'publication_api_response_cache',
                        'sourceTable', 'api_response_cache',
                        'publicationId', current_id),
                    legacy_row_count,
                    legacy_content_hash,
                    'ready',
                    now())
                ON CONFLICT (publication_id, surface_name) DO UPDATE SET
                    binding_kind = EXCLUDED.binding_kind,
                    binding_json = EXCLUDED.binding_json,
                    row_count = EXCLUDED.row_count,
                    content_hash = EXCLUDED.content_hash,
                    status = EXCLUDED.status,
                    built_at = EXCLUDED.built_at;
            END IF;
        END $$;

        DELETE FROM publication_api_response_cache cache
        USING scrape_publication_state publication
        WHERE publication.id = TRUE
          AND cache.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.working_publication_id;

        DELETE FROM publication_api_response_cache_staging cache
        USING scrape_publication_state publication
        WHERE publication.id = TRUE
          AND cache.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND cache.publication_id IS DISTINCT FROM
              publication.working_publication_id;

        UPDATE publication_surface_bindings binding
        SET binding_kind = 'retired_generation_cache',
            binding_json = jsonb_build_object(
                'table', 'publication_api_response_cache',
                'retired', true),
            row_count = 0,
            content_hash = NULL,
            status = 'retired',
            built_at = now()
        FROM scrape_publication_state publication
        WHERE publication.id = TRUE
          AND binding.surface_name = 'api_response_cache'
          AND binding.publication_id IS DISTINCT FROM
              publication.current_publication_id
          AND binding.publication_id IS DISTINCT FROM
              publication.previous_publication_id
          AND binding.publication_id IS DISTINCT FROM
              publication.working_publication_id
          AND binding.status <> 'retired';
        """;
}
