namespace FSTService.Persistence.Maintenance;

public static class SnapshotGenerationRetentionSchema
{
    public const string Sql = """
        DO $retention_schema_admission$
        DECLARE
            worker_row RECORD;
        BEGIN
            IF NOT pg_catalog.pg_try_advisory_xact_lock(
                pg_catalog.hashtextextended(
                    'fst.snapshot-generation-retention-schema', 0))
            THEN
                RAISE EXCEPTION
                    'Snapshot-generation retention schema admission is busy in this database; retry initialization.'
                    USING ERRCODE = '55P03';
            END IF;
            IF pg_catalog.to_regclass('public.snapshot_generation_retention_cycles') IS NOT NULL
                AND NOT EXISTS (
                    SELECT 1 FROM pg_catalog.pg_constraint
                    WHERE conrelid=pg_catalog.to_regclass('public.snapshot_generation_retention_cycles')
                      AND conname='ux_snapshot_generation_retention_cycle_trigger'
                )
            THEN
                IF NOT pg_catalog.pg_try_advisory_xact_lock(5067481511116518500)
                    OR NOT pg_catalog.pg_try_advisory_xact_lock(2026050901)
                    OR NOT pg_catalog.pg_try_advisory_xact_lock_shared(5067481511116519500)
                    OR NOT pg_catalog.pg_try_advisory_xact_lock(2026082301)
                THEN
                    RAISE EXCEPTION
                        'Canonical retention migration requires quiescent legacy writers; retry after the guarded worker stop.'
                        USING ERRCODE='55P03';
                END IF;
                LOCK TABLE ONLY public.service_worker_status IN SHARE MODE NOWAIT;
                SELECT * INTO worker_row FROM public.service_worker_status
                WHERE worker_key='scraper' FOR SHARE NOWAIT;
                IF FOUND THEN
                    IF worker_row.status IS DISTINCT FROM 'offline'
                        OR worker_row.mode IS DISTINCT FROM 'scraper'
                        OR worker_row.current_operation_json IS NOT NULL
                        OR coalesce(pg_catalog.btrim(worker_row.instance_id),'') = ''
                        OR worker_row.started_at IS NULL
                        OR worker_row.last_status_change_at IS NULL
                        OR worker_row.last_heartbeat_at IS NULL
                        OR worker_row.started_at > worker_row.last_status_change_at
                        OR worker_row.last_status_change_at > worker_row.last_heartbeat_at
                        OR worker_row.last_heartbeat_at > pg_catalog.clock_timestamp()
                        OR worker_row.last_status_change_at < pg_catalog.clock_timestamp() - interval '15 minutes'
                    THEN
                        RAISE EXCEPTION
                            'Canonical retention migration refuses an active, unknown, or stale worker; a fresh guarded offline boundary is required.'
                            USING ERRCODE='55000';
                    END IF;
                ELSIF EXISTS (SELECT 1 FROM public.scrape_log) THEN
                    RAISE EXCEPTION
                        'Canonical retention migration requires authoritative worker identity for an existing scrape database.'
                        USING ERRCODE='55000';
                END IF;
                PERFORM id FROM public.scrape_publication_state WHERE id=TRUE FOR SHARE NOWAIT;
                IF EXISTS (SELECT 1 FROM public.scrape_log WHERE status='running')
                    OR EXISTS (
                        SELECT 1 FROM public.scrape_publication_state
                        WHERE public_reads_frozen OR working_publication_id IS NOT NULL
                          OR publication_commit_intent_started_at IS NOT NULL
                          OR max_score_mutation_gate_token IS NOT NULL
                    )
                THEN
                    RAISE EXCEPTION
                        'Canonical retention migration requires completed, unfrozen publication state.'
                        USING ERRCODE='55000';
                END IF;
            END IF;
        END
        $retention_schema_admission$;

        CREATE TABLE IF NOT EXISTS public.snapshot_generation_retention_cycles (
            cycle_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY
                                       PRIMARY KEY,
            trigger_scrape_id          BIGINT NOT NULL
                                       REFERENCES public.scrape_log(id)
                                       ON DELETE RESTRICT,
            trigger_publication_id     BIGINT NOT NULL
                                       REFERENCES public.publication_generations(
                                           publication_id)
                                       ON DELETE RESTRICT,
            safe_point_kind            TEXT NOT NULL,
            safe_point_at              TIMESTAMPTZ NOT NULL,
            planner_version            INTEGER NOT NULL,
            config_version             INTEGER NOT NULL,
            report_only                BOOLEAN NOT NULL DEFAULT TRUE,
            status                     TEXT NOT NULL,
            oracle_agreement           BOOLEAN NOT NULL,
            candidate_identity_hash    TEXT NOT NULL,
            observation_hash           TEXT NOT NULL,
            planner_child_set          JSONB NOT NULL,
            planner_live_set           JSONB NOT NULL,
            planner_candidate_set      JSONB NOT NULL,
            oracle_child_set           JSONB NOT NULL,
            oracle_live_set            JSONB NOT NULL,
            oracle_candidate_set       JSONB NOT NULL,
            candidate_count            INTEGER NOT NULL,
            protected_count            INTEGER NOT NULL,
            blocked_count              INTEGER NOT NULL,
            candidate_bytes            BIGINT NOT NULL,
            global_blockers            JSONB NOT NULL DEFAULT '[]'::jsonb,
            anomalies                  JSONB NOT NULL DEFAULT '[]'::jsonb,
            error_message              TEXT,
            created_at                 TIMESTAMPTZ NOT NULL
                                       DEFAULT pg_catalog.clock_timestamp(),
            CONSTRAINT
                ux_snapshot_generation_retention_cycle_safe_point
                UNIQUE (
                    trigger_scrape_id,
                    trigger_publication_id,
                    safe_point_kind),
            CONSTRAINT
                ck_snapshot_generation_retention_cycle_safe_point
                CHECK (
                    safe_point_kind IN (
                        'terminal_worker_post_publication',
                        'operator_offline_post_publication')),
            CONSTRAINT
                ck_snapshot_generation_retention_cycle_versions
                CHECK (
                    planner_version > 0
                    AND config_version > 0),
            CONSTRAINT
                ck_snapshot_generation_retention_cycle_report_only
                CHECK (report_only),
            CONSTRAINT
                ck_snapshot_generation_retention_cycle_status
                CHECK (
                    status IN (
                        'observed',
                        'blocked',
                        'oracle_mismatch',
                        'failed')),
            CONSTRAINT
                ck_snapshot_generation_retention_cycle_hashes
                CHECK (
                    candidate_identity_hash ~ '^[0-9a-f]{64}$'
                    AND observation_hash ~ '^[0-9a-f]{64}$'),
            CONSTRAINT
                ck_snapshot_generation_retention_cycle_counts
                CHECK (
                    candidate_count >= 0
                    AND protected_count >= 0
                    AND blocked_count >= 0
                    AND candidate_bytes >= 0),
            CONSTRAINT
                ck_snapshot_generation_retention_cycle_oracle
                CHECK (
                    (status = 'oracle_mismatch'
                        AND NOT oracle_agreement
                        AND candidate_count = 0)
                    OR
                    (status IN ('observed', 'blocked')
                        AND oracle_agreement)
                    OR status = 'failed')
        );

        ALTER TABLE public.snapshot_generation_retention_cycles
            ADD COLUMN IF NOT EXISTS anomalies
                JSONB NOT NULL DEFAULT '[]'::jsonb;

        DO $offline_retention_safe_point$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_catalog.pg_constraint
                WHERE conrelid =
                        'public.snapshot_generation_retention_cycles'::regclass
                  AND conname =
                        'ck_snapshot_generation_retention_cycle_safe_point'
                  AND pg_catalog.pg_get_expr(conbin, conrelid, false) =
                    '(safe_point_kind = ANY (ARRAY[''terminal_worker_post_publication''::text, ''operator_offline_post_publication''::text]))'
            ) THEN
                ALTER TABLE public.snapshot_generation_retention_cycles
                    DROP CONSTRAINT IF EXISTS
                        ck_snapshot_generation_retention_cycle_safe_point;
                ALTER TABLE public.snapshot_generation_retention_cycles
                    ADD CONSTRAINT
                        ck_snapshot_generation_retention_cycle_safe_point
                    CHECK (
                        safe_point_kind IN (
                            'terminal_worker_post_publication',
                            'operator_offline_post_publication'));
            END IF;
        END
        $offline_retention_safe_point$;

        DO $canonical_retention_cycle$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM public.snapshot_generation_retention_cycles
                GROUP BY trigger_scrape_id, trigger_publication_id
                HAVING count(*) > 1
            ) THEN
                RAISE EXCEPTION
                    'Duplicate immutable retention cycles require explicit operator adjudication; no evidence was rewritten.'
                    USING ERRCODE = '55000';
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_catalog.pg_constraint
                WHERE conrelid =
                        'public.snapshot_generation_retention_cycles'::regclass
                  AND conname =
                        'ux_snapshot_generation_retention_cycle_trigger'
            ) THEN
                ALTER TABLE public.snapshot_generation_retention_cycles
                    ADD CONSTRAINT ux_snapshot_generation_retention_cycle_trigger
                    UNIQUE (trigger_scrape_id, trigger_publication_id);
            ELSIF NOT EXISTS (
                SELECT 1 FROM pg_catalog.pg_constraint
                WHERE conrelid =
                        'public.snapshot_generation_retention_cycles'::regclass
                  AND conname =
                        'ux_snapshot_generation_retention_cycle_trigger'
                  AND contype = 'u'
                  AND convalidated
                  AND pg_catalog.pg_get_constraintdef(oid, false) =
                        'UNIQUE (trigger_scrape_id, trigger_publication_id)'
            ) THEN
                RAISE EXCEPTION
                    'The canonical retention-cycle constraint does not match the accepted contract.'
                    USING ERRCODE = '55000';
            END IF;
        END
        $canonical_retention_cycle$;

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_cycles_created
            ON public.snapshot_generation_retention_cycles (
                created_at DESC,
                cycle_id DESC);

        CREATE TABLE IF NOT EXISTS
            public.snapshot_generation_retention_observations (
                observation_id             BIGINT
                                           GENERATED BY DEFAULT AS IDENTITY
                                           PRIMARY KEY,
                cycle_id                   BIGINT NOT NULL
                                           REFERENCES
                                               public.snapshot_generation_retention_cycles(
                                                   cycle_id)
                                           ON DELETE RESTRICT,
                report_only                BOOLEAN NOT NULL DEFAULT TRUE,
                instrument                 TEXT NOT NULL,
                root_schema                TEXT NOT NULL,
                root_relation              TEXT NOT NULL,
                snapshot_parent_oid        BIGINT NOT NULL,
                root_oid                   BIGINT NOT NULL,
                root_partition_key         TEXT NOT NULL,
                root_partition_bound       TEXT NOT NULL,
                root_tablespace_name       TEXT NOT NULL,
                root_relation_options      JSONB NOT NULL,
                root_index_configuration   JSONB NOT NULL,
                child_schema               TEXT NOT NULL,
                child_relation             TEXT NOT NULL,
                snapshot_id                BIGINT NOT NULL,
                child_oid                  BIGINT NOT NULL,
                child_relfilenode          BIGINT NOT NULL,
                partition_bound            TEXT NOT NULL,
                tablespace_name            TEXT NOT NULL,
                relation_kind              TEXT NOT NULL,
                persistence_kind           TEXT NOT NULL,
                access_method              TEXT NOT NULL,
                relation_options           JSONB NOT NULL,
                index_configuration        JSONB NOT NULL,
                stable_child_identity_hash TEXT NOT NULL,
                stable_config_schema_hash  TEXT NOT NULL,
                row_estimate               BIGINT NOT NULL,
                total_bytes                BIGINT NOT NULL,
                observation_metrics_hash   TEXT NOT NULL,
                planner_live               BOOLEAN NOT NULL,
                oracle_live                BOOLEAN NOT NULL,
                classification             TEXT NOT NULL,
                root_reasons               TEXT[] NOT NULL
                                           DEFAULT ARRAY[]::TEXT[],
                blocker_codes              TEXT[] NOT NULL
                                           DEFAULT ARRAY[]::TEXT[],
                details                    JSONB NOT NULL
                                           DEFAULT '{}'::jsonb,
                created_at                 TIMESTAMPTZ NOT NULL
                                           DEFAULT pg_catalog.clock_timestamp(),
                CONSTRAINT
                    ux_snapshot_generation_retention_observation_child
                    UNIQUE (
                        cycle_id,
                        instrument,
                        child_oid,
                        child_relfilenode),
                CONSTRAINT
                    ux_snapshot_generation_retention_observation_cycle
                    UNIQUE (cycle_id, observation_id),
                CONSTRAINT
                    ck_snapshot_generation_retention_observation_report_only
                    CHECK (report_only),
                CONSTRAINT
                    ck_snapshot_generation_retention_observation_instrument
                    CHECK (
                        instrument IN (
                            'Solo_Guitar',
                            'Solo_Bass',
                            'Solo_Vocals',
                            'Solo_Drums',
                            'Solo_PeripheralGuitar',
                            'Solo_PeripheralBass',
                            'Solo_PeripheralVocals',
                            'Solo_PeripheralCymbals',
                            'Solo_PeripheralDrums')),
                CONSTRAINT
                    ck_snapshot_generation_retention_observation_class
                    CHECK (
                        classification IN (
                            'candidate',
                            'protected',
                            'blocked',
                            'oracle_mismatch')),
                CONSTRAINT
                    ck_snapshot_generation_retention_observation_identity
                    CHECK (
                        snapshot_id > 0
                        AND snapshot_parent_oid >= 0
                        AND root_oid >= 0
                        AND child_oid > 0
                        AND child_relfilenode > 0
                        AND row_estimate >= 0
                        AND total_bytes >= 0),
                CONSTRAINT
                    ck_snapshot_generation_retention_observation_hashes
                    CHECK (
                        stable_child_identity_hash
                            ~ '^[0-9a-f]{64}$'
                        AND stable_config_schema_hash
                            ~ '^[0-9a-f]{64}$'
                        AND observation_metrics_hash
                            ~ '^[0-9a-f]{64}$'),
                CONSTRAINT
                    ck_snapshot_generation_retention_observation_names
                    CHECK (
                        root_schema <> ''
                        AND root_relation <> ''
                        AND root_partition_key <> ''
                        AND root_partition_bound <> ''
                        AND root_tablespace_name <> ''
                        AND child_schema <> ''
                        AND child_relation <> ''
                        AND partition_bound <> ''
                        AND tablespace_name <> ''
                        AND relation_kind <> ''
                        AND persistence_kind <> ''
                        AND access_method <> ''),
                CONSTRAINT
                    ck_snapshot_generation_retention_observation_agreement
                    CHECK (
                        classification = 'oracle_mismatch'
                        OR planner_live = oracle_live)
            );

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_observations_cycle
            ON public.snapshot_generation_retention_observations (
                cycle_id,
                snapshot_id,
                instrument);

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_observations_identity
            ON public.snapshot_generation_retention_observations (
                instrument,
                snapshot_id,
                child_oid,
                child_relfilenode);

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_observations_snapshot
            ON public.snapshot_generation_retention_observations (
                snapshot_id,
                cycle_id);

        CREATE TABLE IF NOT EXISTS
            public.snapshot_generation_retention_deferrals (
                deferral_id                BIGINT
                                           GENERATED BY DEFAULT AS IDENTITY
                                           PRIMARY KEY,
                trigger_scrape_id          BIGINT NOT NULL
                                           REFERENCES public.scrape_log(id)
                                           ON DELETE RESTRICT,
                trigger_publication_id     BIGINT NOT NULL
                                           REFERENCES public.publication_generations(
                                               publication_id)
                                           ON DELETE RESTRICT,
                safe_point_kind            TEXT NOT NULL,
                safe_point_at              TIMESTAMPTZ NOT NULL,
                report_only                BOOLEAN NOT NULL DEFAULT TRUE,
                code                       TEXT NOT NULL,
                detail                     TEXT NOT NULL,
                retryable                  BOOLEAN NOT NULL,
                evidence                   JSONB NOT NULL
                                           DEFAULT '{}'::jsonb,
                created_at                 TIMESTAMPTZ NOT NULL
                                           DEFAULT pg_catalog.clock_timestamp(),
                CONSTRAINT
                    ck_snapshot_generation_retention_deferral_report_only
                    CHECK (report_only),
                CONSTRAINT
                    ck_snapshot_generation_retention_deferral_safe_point
                    CHECK (
                        safe_point_kind IN (
                            'terminal_worker_post_publication',
                            'operator_offline_post_publication')),
                CONSTRAINT
                    ck_snapshot_generation_retention_deferral_values
                    CHECK (code <> '' AND detail <> '')
            );

        DO $offline_retention_deferral$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_catalog.pg_constraint
                WHERE conrelid =
                        'public.snapshot_generation_retention_deferrals'::regclass
                  AND conname =
                        'ck_snapshot_generation_retention_deferral_safe_point'
                  AND pg_catalog.pg_get_expr(conbin, conrelid, false) =
                    '(safe_point_kind = ANY (ARRAY[''terminal_worker_post_publication''::text, ''operator_offline_post_publication''::text]))'
            ) THEN
                ALTER TABLE public.snapshot_generation_retention_deferrals
                    DROP CONSTRAINT IF EXISTS
                        ck_snapshot_generation_retention_deferral_safe_point;
                ALTER TABLE public.snapshot_generation_retention_deferrals
                    ADD CONSTRAINT
                        ck_snapshot_generation_retention_deferral_safe_point
                    CHECK (
                        safe_point_kind IN (
                            'terminal_worker_post_publication',
                            'operator_offline_post_publication'));
            END IF;
        END
        $offline_retention_deferral$;

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_deferrals_safe_point
            ON public.snapshot_generation_retention_deferrals (
                trigger_publication_id,
                created_at DESC);

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_deferrals_scrape
            ON public.snapshot_generation_retention_deferrals (
                trigger_scrape_id,
                deferral_id);

        CREATE TABLE IF NOT EXISTS
            public.snapshot_generation_retention_holds (
                hold_id                    BIGINT
                                           GENERATED BY DEFAULT AS IDENTITY
                                           PRIMARY KEY,
                instrument                 TEXT NOT NULL,
                snapshot_id                BIGINT NOT NULL
                                           REFERENCES public.scrape_log(id)
                                           ON DELETE RESTRICT,
                hold_kind                  TEXT NOT NULL,
                reason                     TEXT NOT NULL,
                created_by                 TEXT NOT NULL,
                created_at                 TIMESTAMPTZ NOT NULL
                                           DEFAULT pg_catalog.clock_timestamp(),
                released_by                TEXT,
                released_at                TIMESTAMPTZ,
                release_reason             TEXT,
                CONSTRAINT
                    ck_snapshot_generation_retention_hold_instrument
                    CHECK (
                        instrument IN (
                            'Solo_Guitar',
                            'Solo_Bass',
                            'Solo_Vocals',
                            'Solo_Drums',
                            'Solo_PeripheralGuitar',
                            'Solo_PeripheralBass',
                            'Solo_PeripheralVocals',
                            'Solo_PeripheralCymbals',
                            'Solo_PeripheralDrums')),
                CONSTRAINT
                    ck_snapshot_generation_retention_hold_kind
                    CHECK (
                        hold_kind IN (
                            'operator',
                            'retention_in_flight',
                            'restore_in_flight')),
                CONSTRAINT
                    ck_snapshot_generation_retention_hold_values
                    CHECK (
                        snapshot_id > 0
                        AND reason <> ''
                        AND created_by <> ''),
                CONSTRAINT
                    ck_snapshot_generation_retention_hold_release
                    CHECK (
                        (released_at IS NULL
                            AND released_by IS NULL
                            AND release_reason IS NULL)
                        OR
                        (released_at IS NOT NULL
                            AND released_by IS NOT NULL
                            AND release_reason IS NOT NULL))
            );

        CREATE UNIQUE INDEX IF NOT EXISTS
            ux_snapshot_generation_retention_active_hold
            ON public.snapshot_generation_retention_holds (
                instrument,
                snapshot_id,
                hold_kind)
            WHERE released_at IS NULL;

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_holds_snapshot
            ON public.snapshot_generation_retention_holds (
                snapshot_id,
                hold_id);

        CREATE INDEX IF NOT EXISTS
            ix_leaderboard_published_scope_source_source_scrape
            ON public.leaderboard_published_scope_source (
                source_scrape_id,
                published_scrape_id);

        CREATE TABLE IF NOT EXISTS
            public.snapshot_generation_retention_evidence (
                evidence_id                BIGINT
                                           GENERATED BY DEFAULT AS IDENTITY
                                           PRIMARY KEY,
                cycle_id                   BIGINT NOT NULL
                                           REFERENCES
                                               public.snapshot_generation_retention_cycles(
                                                   cycle_id)
                                           ON DELETE RESTRICT,
                observation_id             BIGINT,
                sequence                   INTEGER NOT NULL,
                phase                      TEXT NOT NULL,
                kind                       TEXT NOT NULL,
                payload                    JSONB NOT NULL,
                previous_hash              TEXT,
                current_hash               TEXT NOT NULL,
                created_at                 TIMESTAMPTZ NOT NULL
                                           DEFAULT pg_catalog.clock_timestamp(),
                CONSTRAINT
                    fk_snapshot_generation_retention_evidence_observation
                    FOREIGN KEY (cycle_id, observation_id)
                    REFERENCES
                        public.snapshot_generation_retention_observations(
                            cycle_id,
                            observation_id)
                    ON DELETE RESTRICT,
                CONSTRAINT
                    ux_snapshot_generation_retention_evidence_sequence
                    UNIQUE (cycle_id, sequence),
                CONSTRAINT
                    ck_snapshot_generation_retention_evidence_values
                    CHECK (
                        sequence > 0
                        AND phase <> ''
                        AND kind <> ''),
                CONSTRAINT
                    ck_snapshot_generation_retention_evidence_hashes
                    CHECK (
                        (previous_hash IS NULL
                            OR previous_hash ~ '^[0-9a-f]{64}$')
                        AND current_hash ~ '^[0-9a-f]{64}$')
            );

        CREATE INDEX IF NOT EXISTS
            ix_snapshot_generation_retention_evidence_observation
            ON public.snapshot_generation_retention_evidence (
                observation_id,
                sequence)
            WHERE observation_id IS NOT NULL;

        CREATE TABLE IF NOT EXISTS public.snapshot_generation_retention_worker_configuration (
            worker_instance_id TEXT PRIMARY KEY CHECK (worker_instance_id <> ''),
            report_only_enabled BOOLEAN NOT NULL,
            planner_version INTEGER NOT NULL CHECK (planner_version > 0),
            config_version INTEGER NOT NULL CHECK (config_version > 0),
            canonical_cycle_identity_version INTEGER NOT NULL
                CHECK (canonical_cycle_identity_version > 0),
            worker_code_sha256 TEXT NOT NULL CHECK (worker_code_sha256 ~ '^[0-9a-f]{64}$'),
            configuration_sha256 TEXT NOT NULL CHECK (configuration_sha256 ~ '^[0-9a-f]{64}$'),
            configured_at TIMESTAMPTZ NOT NULL DEFAULT pg_catalog.clock_timestamp()
        );

        CREATE OR REPLACE FUNCTION
            public.fst_reject_snapshot_generation_retention_evidence_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $retention_immutable$
        BEGIN
            RAISE EXCEPTION
                'Snapshot-generation retention report evidence is immutable.'
                USING ERRCODE = '55000';
        END
        $retention_immutable$;

        DO $retention_triggers$
        DECLARE
            relation_name TEXT;
            trigger_name TEXT;
        BEGIN
            FOREACH relation_name IN ARRAY ARRAY[
                'snapshot_generation_retention_cycles',
                'snapshot_generation_retention_observations',
                'snapshot_generation_retention_deferrals',
                'snapshot_generation_retention_evidence',
                'snapshot_generation_retention_worker_configuration'
            ]
            LOOP
                trigger_name := CASE
                    WHEN relation_name = 'snapshot_generation_retention_worker_configuration'
                    THEN 'trg_reject_retention_worker_configuration_mutation'
                    ELSE 'trg_reject_' || relation_name || '_mutation'
                END;
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_catalog.pg_trigger trigger_row
                    WHERE trigger_row.tgrelid =
                            pg_catalog.to_regclass(
                                'public.' || relation_name)
                      AND trigger_row.tgname = trigger_name
                      AND NOT trigger_row.tgisinternal
                ) THEN
                    EXECUTE pg_catalog.format(
                        'CREATE TRIGGER %I BEFORE UPDATE OR DELETE OR TRUNCATE ON public.%I FOR EACH STATEMENT EXECUTE FUNCTION public.fst_reject_snapshot_generation_retention_evidence_mutation()',
                        trigger_name,
                        relation_name);
                END IF;
                IF relation_name = 'snapshot_generation_retention_worker_configuration'
                    AND EXISTS (
                        SELECT 1 FROM pg_catalog.pg_trigger
                        WHERE tgrelid=pg_catalog.to_regclass('public.' || relation_name)
                          AND tgname=pg_catalog.left('trg_reject_' || relation_name || '_mutation',63)
                    )
                THEN
                    EXECUTE pg_catalog.format('DROP TRIGGER %I ON public.%I',
                        pg_catalog.left('trg_reject_' || relation_name || '_mutation',63),relation_name);
                END IF;
            END LOOP;
        END
        $retention_triggers$;
        """;
}
