# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FortniteFestivalRN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix NitroModules build: ThreadUtils.cpp includes UIThreadDispatcher.hpp
    # from a sibling directory. Add all ios/ subdirectories as header search paths.
    nitro_target = installer.pods_project.targets.find { |t| t.name == 'NitroModules' }
    if nitro_target
      nitro_target.build_configurations.each do |config|
        nitro_root = File.join(installer.sandbox.pod_dir('NitroModules'), 'ios')
        subdirs = Dir.glob(File.join(nitro_root, '**')).select { |f| File.directory?(f) }
        existing = config.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
        config.build_settings['HEADER_SEARCH_PATHS'] = [existing, *subdirs].join(' ')
      end
    end
  end
end
