import { describe, expect, it } from 'vitest';
import serviceInfoEnglish from '../../../src/pages/settings/serviceInfo.en.json';

describe('Settings service progress labels', () => {
  it('keeps the approved friendly phase catalog', () => {
    expect(serviceInfoEnglish.phaseLabels).toEqual({
      scrape_leaderboards: 'Scraping Leaderboard Scores',
      post_rank_recompute: 'Post-Scrape Enrichment',
      post_first_seen_season: 'Post-Scrape Enrichment',
      post_account_name_resolution: 'Resolving Player Names',
      post_refresh_registered_users: 'Refreshing Registered Users',
      post_activate_shadow_snapshots_early: 'Snapshot Preparation',
      post_band_extraction: 'Extracting Band Context',
      post_legacy_band_scrape: 'Fetching Legacy Band Leaderboards',
      post_registered_player_band_discovery: 'Registered Player Band Discovery',
      post_registered_band_targeted_processing: 'Registered Band Processing',
      post_deferred_registration_sync: 'Deferred Registration Sync',
      post_band_maintenance: 'Band Maintenance',
      post_compute_rankings: 'Computing Rankings',
      post_prepare_solo_current_projection: 'Preparing Current Solo Rankings',
      post_rivals: 'Computing Player Rivals',
      post_leaderboard_rivals: 'Calculating Leaderboard Rivals',
      post_player_stats_tiers: 'Computing Player Statistics',
      post_checkpoint: 'Checkpoint',
      post_activate_shadow_snapshots: 'Finalizing Updated Leaderboard Data',
      post_seal_solo_current_projection: 'Finalizing Solo Ranking Scopes',
      post_cleanup_solo_current_projection: 'Solo Projection Cleanup',
      post_cleanup_precompute_all: 'API Precompute Cleanup',
      post_cleanup_solo_excess_entries: 'Solo Entry Cleanup',
      post_cleanup_rank_history_retention: 'Solo Rank History Cleanup',
      post_cleanup_band_rank_history_retention: 'Band Rank History Cleanup',
      post_cleanup_service_level_retention: 'Retention',
      publication_commit: 'Publishing Leaderboard Update',
      post_improvement_notifications: 'Preparing Improvement Notifications',
    });
  });

  it('keeps the approved friendly static subphase catalog', () => {
    expect(serviceInfoEnglish.subphaseLabels).toEqual({
      fetching_leaderboards: 'Fetching Leaderboards',
      persisting_scores: 'Saving Retrieved Scores',
      deep_scraping: 'Fetching Extended Leaderboard Data',
      cancelling_band_after_solo_failure: 'Stopping Band Leaderboard Fetch',
      draining_solo_writes: 'Saving Leaderboard Scores',
      dropping_solo_indexes: 'Preparing Solo Score Storage',
      flushing_solo: 'Saving Solo Leaderboard Scores',
      creating_solo_indexes: 'Optimizing Solo Score Storage',
      detecting_score_changes: 'Detecting Score Changes',
      checkpointing: 'Saving Scrape Checkpoint',
      updating_population: 'Updating Leaderboard Totals',
      awaiting_band: 'Fetching Band Leaderboards',
      skipping_band_after_timeout: 'Continuing Without Band Leaderboards',
      dropping_band_indexes: 'Preparing Band Score Storage',
      flushing_band: 'Saving Band Leaderboard Scores',
      creating_band_indexes: 'Optimizing Band Score Storage',
      discovering_season_windows: 'Finding Festival Seasons',
      building_work_list: 'Preparing Player Sync Work',
      processing_songs: 'Refreshing Player Scores',
      completing_user_actions: 'Finalizing Player Sync',
      per_song_rivals: 'Calculating Player Rivals',
      population_tiers: 'Calculating Leaderboard Percentiles',
      parallel_precompute: 'Preparing Published API Data',
      extracting_band_context: 'Processing Band Score Data',
      rebuilding_band_membership_summary: 'Refreshing Band Membership',
      per_instrument_rankings: 'Calculating Instrument Rankings',
      composite_rankings: 'Calculating Overall Rankings',
      solo_family_rankings: 'Calculating Solo Rankings',
      combo_rankings: 'Calculating Combined Rankings',
      rank_history_and_band_rankings: 'Calculating Rank History and Band Rankings',
      band_rankings: 'Calculating Band Rankings',
      rank_history_snapshots: 'Saving Rank History',
      activating_shadow_snapshots_early: 'Preparing Updated Leaderboard Data',
      registered_player_band_discovery: 'Finding Registered Player Bands',
      registered_band_targeted_processing: 'Refreshing Registered Bands',
      maintaining_band_projection: 'Refreshing Band Data',
      prune: 'Removing Outdated Band Entries',
      search_projection_refresh: 'Refreshing Band Search Data',
      current_projection_refresh: 'Refreshing Current Band Rankings',
      final_checkpoint: 'Saving Final Checkpoint',
      publication_cleanup: 'Preparing Data for Publication',
      deferred_registration_sync: 'Syncing Deferred Registrations',
      database_cleanup: 'Cleaning Database',
      cleanup_solo_excess_entries: 'Removing Extra Solo Scores',
      cleanup_service_level_retention: 'Planning Data Retention',
      cleanup_api_precompute: 'Preparing API Responses',
      cleanup_solo_current_projection: 'Refreshing Current Solo Rankings',
      cleanup_composite_rank_history: 'Cleaning Overall Rank History',
      enriching_parallel_rank_recompute: 'Recomputing Changed Ranks',
      enriching_parallel_tail: 'Calculating Seasons and Resolving Names',
    });
  });
});
