import type { CSSProperties } from 'react';
import {
  Align,
  Border,
  BoxSizing,
  Colors,
  CssProp,
  CssValue,
  Cursor,
  Display,
  Font,
  Gap,
  Justify,
  Layout,
  LINK_TRANSITION_MS,
  Overflow,
  Radius,
  Weight,
  border,
  flexColumn,
  flexRow,
  padding,
  purpleGlass,
  transition,
  transitions,
} from '@festival/theme';

const quickLinkTransition = transitions(
  transition(CssProp.backgroundColor, LINK_TRANSITION_MS),
  transition(CssProp.borderColor, LINK_TRANSITION_MS),
  transition(CssProp.boxShadow, LINK_TRANSITION_MS),
  transition(CssProp.color, LINK_TRANSITION_MS),
);

export const playerPageStyles = {
  scrollArea: { overflowX: Overflow.visible } as CSSProperties,
  gridList: {
    display: Display.grid,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: Gap.md,
    minWidth: 0,
    overflow: Overflow.hidden,
  } as CSSProperties,
  gridFullWidth: { gridColumn: '1 / -1' } as CSSProperties,
  sectionLandmark: {
    minWidth: 0,
    scrollMarginTop: Gap.md,
  } as CSSProperties,
  quickLinksOverlay: {
    minWidth: 0,
    width: Layout.sidebarWidth,
    height: '100%',
    flexShrink: 0,
    pointerEvents: 'auto',
    display: Display.flex,
  } as CSSProperties,
  quickLinksSticky: {
    ...flexColumn,
    flex: 1,
    gap: Gap.xs,
    width: '100%',
    height: '100%',
    maxHeight: '100%',
    minWidth: 0,
    boxSizing: BoxSizing.borderBox,
    padding: padding(Gap.md, 0, Gap.md, Gap.md),
    overflowX: Overflow.visible,
    overflowY: Overflow.auto,
    overscrollBehavior: 'contain' as const,
  } as CSSProperties,
  quickLinkButton: {
    ...flexRow,
    alignItems: Align.center,
    justifyContent: Justify.flexStart,
    flexShrink: 0,
    gap: Gap.lg,
    width: '100%',
    height: Layout.entryRowHeight,
    minWidth: 0,
    padding: padding(0, Gap.xl),
    color: Colors.textPrimary,
    textDecoration: CssValue.none,
    fontSize: Font.lg,
    fontWeight: Weight.semibold,
    borderRadius: Radius.full,
    boxSizing: BoxSizing.borderBox,
    backgroundColor: CssValue.transparent,
    border: border(Border.thin, CssValue.transparent),
    boxShadow: CssValue.none,
    transition: quickLinkTransition,
    cursor: Cursor.pointer,
    textAlign: 'left' as const,
    '--frosted-card': '1',
  } as CSSProperties,
  quickLinkButtonActive: {
    ...purpleGlass,
    ...flexRow,
    alignItems: Align.center,
    justifyContent: Justify.flexStart,
    flexShrink: 0,
    gap: Gap.lg,
    width: '100%',
    height: Layout.entryRowHeight,
    minWidth: 0,
    padding: padding(0, Gap.xl),
    color: Colors.textPrimary,
    textDecoration: CssValue.none,
    fontSize: Font.lg,
    fontWeight: Weight.semibold,
    borderRadius: Radius.full,
    boxSizing: BoxSizing.borderBox,
    boxShadow: CssValue.none,
    cursor: Cursor.pointer,
    textAlign: 'left' as const,
  } as CSSProperties,
  quickLinkIcon: {
    ...flexRow,
    width: 20,
    flexShrink: 0,
    justifyContent: Justify.center,
    overflow: Overflow.visible,
  } as CSSProperties,
  quickLinkLabel: {
    display: Display.flex,
    alignItems: Align.center,
    minWidth: 0,
    flex: 1,
  } as CSSProperties,
} as const;
